/control/verbose 0
/tracking/verbose 0
/event/verbose 0
/gps/verbose 2

/gps/particle gamma  
 
#/gps/pos/type Plane	#Source shape
/gps/pos/type Beam	#Source shape
/gps/pos/shape Circle
/gps/pos/radius 0.1 mm
/gps/pos/centre 0 0 0.3 mm 
/gps/direction 0 0 -1
/gps/ene/type User
/gps/hist/type energy

# spectra
/gps/hist/point  0.00588  8.2   	
/gps/hist/point  0.00589  16.20   	
/gps/hist/point  0.00649  1.89 	

/gps/ang/type iso 		
#/gps/ang/rot1 1 0 0    
#/gps/ang/rot2 0 0 -1

/gps/ang/mintheta  0
/gps/ang/maxtheta  45
/gps/ang/minphi  0
/gps/ang/maxphi  360. deg 

/gps/source/list

#/jadepix/event/setPrintModulo 100
#/jadepix/beam/type gauss 10 1
#/jadepix/beam/frames 1
#/jadepix/beam/on 

/jadepix/event/setPrintModulo 100
/run/beamOn 1000
